name: "Apply version label to pre-release issue"
description: "Automatically apply a version label to issues tagged with pre-release."

branding:
  icon: "tag"
  color: "red"

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
