name: "Apply version label to issue with specific label"
description: "Automatically apply a version label to issues tagged with a specific label."

branding:
  icon: "tag"
  color: "red"

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true
  required-label:
    description: The required label for this action to run.
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
